In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np
import torch

https://www.analyticsvidhya.com/blog/2019/09/introduction-to-pytorch-from-scratch/?utm_source=blog&utm_medium=image_classification_model_using_CNN_in_PyTorch_vs_TensorFlow

In [3]:
#  setting the random seed for numpy
print("In Numpy: \n")
np.random.seed(42)
# matrix of random numbers
print(np.random.rand(3,2)) 
print(np.random.randn(3,3),"\n") # also print random num from -ve axis and follows normal dist.


#### Try same in torch
print("In torch: \n")
torch.manual_seed(42)
print(torch.rand(3,3))



In Numpy: 

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]] 

In torch: 

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


In [4]:
torch.manual_seed(42)
a = torch.randint(0,10, size = (3,3))
b = torch.randint(1,10, size = (3,3))
print(a,"\n",b, "\n")
# matrix addition
# print(torch.add(a,b), '\n')
# print(a+b, '\n')

# matrix subtraction
# print(torch.sub(a,b), '\n')

# matrix multiplication
# print(torch.mm(a,b), '\n')

# elementwise multiplication
print(a*b, '\n')

# # matrix division
# print(torch.div(a,b))

tensor([[2, 7, 6],
        [4, 6, 5],
        [0, 4, 0]]) 
 tensor([[3, 5, 5],
        [9, 1, 1],
        [5, 3, 5]]) 

tensor([[ 6, 35, 30],
        [36,  6,  5],
        [ 0, 12,  0]]) 



In [5]:
# concatenating vertically (adding row-wise, column number=fixed)
torch.cat((a,b)) 

tensor([[2, 7, 6],
        [4, 6, 5],
        [0, 4, 0],
        [3, 5, 5],
        [9, 1, 1],
        [5, 3, 5]])

In [6]:
# concatenating horizontally (adding column-wise, row number=fixed)
torch.cat((a,b), dim=0)

tensor([[2, 7, 6],
        [4, 6, 5],
        [0, 4, 0],
        [3, 5, 5],
        [9, 1, 1],
        [5, 3, 5]])

In [7]:
# initializing a numpy array
a = np.array([[1,2],[3,4]])
print(a, '\n')

# converting the numpy array to tensor
tensor = torch.from_numpy(a)
print(tensor)

[[1 2]
 [3 4]] 

tensor([[1, 2],
        [3, 4]])


In [8]:
# calculate gradient 
a = torch.ones((2,2), requires_grad=True)
b = a + 5
c = b.mean()
c = c**2
# c = c + 56

print(b,c)

# back propagating
c.backward()

# computing gradients
print(a.grad)


tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(36., grad_fn=<PowBackward0>)
tensor([[3., 3.],
        [3., 3.]])


In [15]:
torch.manual_seed(42)
a = torch.randint(0, 10,size = (3,2))

a,a.t()

(tensor([[2, 7],
         [6, 4],
         [6, 5]]),
 tensor([[2, 6, 6],
         [7, 4, 5]]))

Several optimizer:
* SGD
* Adam
* Adadelta
* Adagrad
* AdamW
* SparseAdam
* Adamax
* ASGD (Averaged Stochastic Gradient Descent)
* RMSprop
* Rprop (resilient backpropagation